# Book settings
# -------------
title: Oppimateriaalia
author: <a href="https://luma-lapinamk.pub">LUMA</a> (<a href="mailto:luma@lapinamk.fi">luma@lapinamk.fi</a>), <a href="https://www.lapinamk.fi">Lapin AMK</a> 
copyright: "2022"
logo: images/logo.png
email: "luma@lapinamk.fi"

# Execution settings
# -------------------
execute:
  execute_notebooks: force

# GitHub-settings
# ----------------
repository:
  url: https://github.com/luma-lapinamk/luma-kirja
  branch: master

# HTML-settings
# --------------
html:
  baseurl: "https://luma-lapinamk.pub"
  use_issues_button: false
  use_repository_button: true
  extra_navbar: <a href="https://jupyterbook.org">Jupyter Book</a> voimaa
