# Book settings
# -------------
title: Oppimateriaalia
author: LUMA-tiimi, Lapin AMK
logo: images/logo.png

# Execution settings
# -------------------
execute:
  execute_notebooks: force

# GitHub-settings
# ----------------
repository:
  url: https://github.com/luma-lapinamk/luma-lapinamk
  branch: master

# HTML-settings
# --------------
html:
  use_issues_button: false
  use_repository_button: true
  extra_navbar: <a href="https://jupyterbook.org">Jupyter Book</a> voimaa
